import type { DesignIssue } from "@/types/design-issue";

export const CATEGORIES = [
  "All Categories",
  "Typography",
  "Color",
  "Spacing",
  "Layout",
  "Hierarchy",
  "Consistency",
  "Accessibility",
];

export const MOCK_ISSUES: DesignIssue[] = [
  {
    id: "1",
    title: "Too Many Font Sizes",
    category: "Typography",
    severity: "moderate",
    body: "Using more than 3–4 font sizes on a single page creates visual chaos. Readers can't tell what's important because everything competes for attention. A clear type scale creates hierarchy without shouting.",
    how_to_fix: "Establish a type scale with no more than 4–5 sizes. Use a modular scale (e.g., 1.25 ratio) and stick to it across every page. Define heading, subheading, body, and caption sizes — then stop.",
    published: true,
    order_index: 1,
  },
  {
    id: "2",
    title: "Low Contrast Text",
    category: "Color",
    severity: "major",
    body: "Light gray text on a white background might look 'clean,' but it fails accessibility standards and frustrates users. If people can't read your content, nothing else about the design matters.",
    how_to_fix: "Check every text/background pair against WCAG AA standards (4.5:1 for body text, 3:1 for large text). Use a contrast checker tool and never go below these ratios.",
    published: true,
    order_index: 2,
  },
  {
    id: "3",
    title: "Inconsistent Spacing",
    category: "Spacing",
    severity: "moderate",
    body: "Random padding and margins throughout a layout make it feel unprofessional. When elements don't align to a consistent rhythm, users sense something is off even if they can't name it.",
    how_to_fix: "Use a 4px or 8px base grid. Every margin, padding, and gap should be a multiple of your base unit. This creates automatic visual harmony.",
    published: true,
    order_index: 3,
  },
  {
    id: "4",
    title: "Missing Visual Hierarchy",
    category: "Hierarchy",
    severity: "major",
    body: "When everything on the page has equal visual weight, nothing stands out. Users don't know where to look first, what's important, or what action to take. Flat designs aren't the same as flat hierarchy.",
    how_to_fix: "Use size, weight, color, and whitespace to create 3 clear levels: primary (what users see first), secondary (supporting info), and tertiary (details). Squint at your design — the hierarchy should be obvious.",
    published: true,
    order_index: 4,
  },
  {
    id: "5",
    title: "Orphaned Headings",
    category: "Typography",
    severity: "minor",
    body: "A heading that sits at the bottom of a column or page, separated from the content it introduces, breaks the reader's flow. The heading belongs to what follows it, not what precedes it.",
    how_to_fix: "Ensure headings always have more space above them than below. The space below a heading should be less than the paragraph spacing, pulling content toward its label.",
    published: true,
    order_index: 5,
  },
  {
    id: "6",
    title: "Clashing Colors",
    category: "Color",
    severity: "moderate",
    body: "Combining colors without understanding undertones or relationships leads to palettes that feel amateur. Two individually nice colors can look terrible together if their temperatures clash.",
    how_to_fix: "Use a color tool (Coolors, Realtime Colors) to build palettes based on color theory. Limit your palette to 1 primary, 1 accent, and 2–3 neutrals. Test combinations with real content.",
    published: true,
    order_index: 6,
  },
  {
    id: "7",
    title: "Walls of Text",
    category: "Layout",
    severity: "moderate",
    body: "Long, unbroken paragraphs on screen are exhausting. Users scan — they don't read linearly. Dense blocks of text signal 'this will take effort' and users bounce.",
    how_to_fix: "Break content into short paragraphs (2–3 sentences max). Use subheadings, bullet points, and whitespace to create scannable sections. Every paragraph should make one point.",
    published: true,
    order_index: 7,
  },
  {
    id: "8",
    title: "Button Style Soup",
    category: "Consistency",
    severity: "minor",
    body: "When buttons across your app look different — different radii, colors, sizes, padding — users can't build a mental model of your interface. Consistency is trust.",
    how_to_fix: "Define 3 button tiers: primary (one clear CTA), secondary (supporting actions), and ghost/text (tertiary). Use these consistently everywhere. Never create a one-off button style.",
    published: true,
    order_index: 8,
  },
  {
    id: "9",
    title: "Ignoring Line Length",
    category: "Typography",
    severity: "minor",
    body: "Lines of text that stretch across the full width of a large screen are hard to track. Readers lose their place jumping from the end of one line to the start of the next.",
    how_to_fix: "Keep line length between 50–75 characters for body text. Use max-width on text containers. A good rule: if you can fit more than ~15 words per line, the container is too wide.",
    published: true,
    order_index: 9,
  },
  {
    id: "10",
    title: "No Focus States",
    category: "Accessibility",
    severity: "major",
    body: "Removing or forgetting to style focus indicators makes your site unusable for keyboard users. This isn't optional — it's a basic accessibility requirement.",
    how_to_fix: "Never set outline: none without providing an alternative. Use visible focus rings (2px+ solid, contrasting color) on all interactive elements. Test by tabbing through your entire UI.",
    published: true,
    order_index: 10,
  },
  {
    id: "11",
    title: "Decorative Overload",
    category: "Layout",
    severity: "minor",
    body: "Shadows, gradients, borders, and background textures piled together create noise. Each decorative element should earn its place by serving a purpose — separation, depth, or emphasis.",
    how_to_fix: "Audit every decorative element. Ask: does this help the user understand the content better? If not, remove it. Start minimal and add decoration only when it solves a problem.",
    published: true,
    order_index: 11,
  },
  {
    id: "12",
    title: "Icon Inconsistency",
    category: "Consistency",
    severity: "minor",
    body: "Mixing icon styles (outlined + filled, different stroke weights, different visual metaphors) makes an interface feel cobbled together from different kits.",
    how_to_fix: "Pick one icon family and stick to it. Use either all outlined or all filled. Ensure consistent size (typically 20–24px) and stroke weight across your entire app.",
    published: true,
    order_index: 12,
  },
];
